import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <main className="container mx-auto grid items-start gap-10 py-8">
        {children}
      </main>
    </div>
  );
}
